networks:
  Roboshop:

services:
  web:
    image: web:1.0.0
    ports:
      - "80:80"
    depends_on:
      - catalogue

  mongodb:
    image: mongodb:1.0.0

  catalogue:
    image: catalogue:1.0.0
      - mongodb


  
