networks:
  Roboshop:

services:
  web:
    image: web:1.0.0
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment

  mongodb:
    image: mongodb:1.0.0

  catalogue:
    image: catalogue:1.0.0
    depends_on:
      - mongodb

  redis:
    image: redis
  
  mysql:
    image: mysql:1.0.0

  user:
    image: user:1.0.0
    depends_on:
      - mongodb
      - redis
      
  cart:
    image: cart:1.0.0
    depends_on:
      - redis
      - catalogue
  shipping:
    image: shipping:1.0.0
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=Roboshop
      - RABBITMQ_DEFAULT_PASS=Roboshop123
  payment:
    image: payment
    depends_on:
      - rabbitmq

  
